src/Entity/Personal.php
<?php

namespace App\Entity;

use App\Repository\PersonalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: PersonalRepository::class)]
class Personal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $identificacion = null;

    #[ORM\Column(length: 255)]
    private ?string $lugar_expedicion = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $apellido = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_cuenta = null;

    #[ORM\Column(length: 255)]
    private ?string $direccion = null;

    #[ORM\Column(nullable: true)]
    private ?string $telefono = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $correo_electronico = null;

    #[ORM\Column(nullable: true)]
    private ?string $celular = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $f_nacimiento = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $f_ingreso = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $f_examen_ingreso = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Sexo $sexo = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Afp $afp = null;

    #[ORM\ManyToOne(inversedBy: 'personals')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Eps $eps = null;

    #[ORM\ManyToOne(inversedBy: 'personals')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Afc $afc = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?TipoCuenta $tipo_cuenta = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?TallaUniforme $talla_uniforme = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?TallaBotas $talla_botas = null;

    #[ORM\ManyToOne(inversedBy: 'personals')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cargo $cargo = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?TallaGuantes $talla_guantes = null;

    #[ORM\ManyToOne(inversedBy: 'personals')]
    private ?CursoEspecializado $curso_especializado = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?TallaCamisa $talla_camisa = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?TallaPantalon $talla_pantalon = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?TallaCalzado $talla_calzado = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'personal', targetEntity: Contrato::class)]
    private Collection $contratos;

    #[ORM\OneToMany(mappedBy: 'personal', targetEntity: ContratoPersonal::class)]
    private Collection $contratoPersonals;

    #[ORM\Column]
    private ?bool $activo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_creacion = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_actualizacion = null;

    #[ORM\Column(type: 'uuid', nullable: true)]
    private ?Uuid $slug;

    #[ORM\Column(nullable: true)]
    private ?int $coorserpark = null;

    #[ORM\OneToMany(mappedBy: 'personal', targetEntity: Prestamo::class)]
    private Collection $prestamos;

    #[ORM\OneToMany(mappedBy: 'personal_id', targetEntity: NovedadNomina::class)]
    private Collection $novedadesNominas;

    public function __construct()
    {
        $this->contratos = new ArrayCollection();
        $this->contratoPersonals = new ArrayCollection();
        $this->slug = Uuid::v6();
        $this->prestamos = new ArrayCollection();
        $this->novedadesNominas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdentificacion(): ?string
    {
        return $this->identificacion;
    }

    public function setIdentificacion(string $identificacion): self
    {
        $this->identificacion = $identificacion;

        return $this;
    }

    public function getLugarExpedicion(): ?string
    {
        return $this->lugar_expedicion;
    }

    public function setLugarExpedicion(string $lugar_expedicion): self
    {
        $this->lugar_expedicion = $lugar_expedicion;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    public function setApellido(string $apellido): self
    {
        $this->apellido = $apellido;

        return $this;
    }

    public function getNumeroCuenta(): ?string
    {
        return $this->numero_cuenta;
    }

    public function setNumeroCuenta(string $numero_cuenta): self
    {
        $this->numero_cuenta = $numero_cuenta;

        return $this;
    }
    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getCorreoElectronico(): ?string
    {
        return $this->correo_electronico;
    }

    public function setCorreoElectronico(?string $correo_electronico): self
    {
        $this->correo_electronico = $correo_electronico;

        return $this;
    }

    public function getCelular(): ?string
    {
        return $this->celular;
    }

    public function setCelular(?string $celular): self
    {
        $this->celular = $celular;

        return $this;
    }

    public function getFNacimiento(): ?\DateTimeInterface
    {
        return $this->f_nacimiento;
    }

    public function setFNacimiento(\DateTimeInterface $f_nacimiento): self
    {
        $this->f_nacimiento = $f_nacimiento;

        return $this;
    }

    public function getFIngreso(): ?\DateTimeInterface
    {
        return $this->f_ingreso;
    }

    public function setFIngreso(\DateTimeInterface $f_ingreso): self
    {
        $this->f_ingreso = $f_ingreso;

        return $this;
    }

    public function getFExamenIngreso(): ?\DateTimeInterface
    {
        return $this->f_examen_ingreso;
    }

    public function setFExamenIngreso(\DateTimeInterface $f_examen_ingreso): self
    {
        $this->f_examen_ingreso = $f_examen_ingreso;

        return $this;
    }

    public function getSexo(): ?Sexo
    {
        return $this->sexo;
    }

    public function setSexo(?Sexo $sexo): self
    {
        $this->sexo = $sexo;

        return $this;
    }

    public function getAfp(): ?Afp
    {
        return $this->afp;
    }

    public function setAfp(?Afp $afp): self
    {
        $this->afp = $afp;

        return $this;
    }

    public function getEps(): ?Eps
    {
        return $this->eps;
    }

    public function setEps(?Eps $eps): self
    {
        $this->eps = $eps;

        return $this;
    }

    public function getAfc(): ?Afc
    {
        return $this->afc;
    }

    public function setAfc(?Afc $afc): self
    {
        $this->afc = $afc;

        return $this;
    }

    public function getTipoCuenta(): ?TipoCuenta
    {
        return $this->tipo_cuenta;
    }

    public function setTipoCuenta(?TipoCuenta $tipo_cuenta): self
    {
        $this->tipo_cuenta = $tipo_cuenta;

        return $this;
    }

    public function getTallaUniforme(): ?TallaUniforme
    {
        return $this->talla_uniforme;
    }

    public function setTallaUniforme(?TallaUniforme $talla_uniforme): self
    {
        $this->talla_uniforme = $talla_uniforme;

        return $this;
    }

    public function getTallaBotas(): ?TallaBotas
    {
        return $this->talla_botas;
    }

    public function setTallaBotas(?TallaBotas $talla_botas): self
    {
        $this->talla_botas = $talla_botas;

        return $this;
    }

    public function getCargo(): ?Cargo
    {
        return $this->cargo;
    }

    public function setCargo(?Cargo $cargo): self
    {
        $this->cargo = $cargo;

        return $this;
    }

    public function getTallaGuantes(): ?TallaGuantes
    {
        return $this->talla_guantes;
    }

    public function setTallaGuantes(?TallaGuantes $talla_guantes): self
    {
        $this->talla_guantes = $talla_guantes;

        return $this;
    }

    public function getCursoEspecializado(): ?CursoEspecializado
    {
        return $this->curso_especializado;
    }

    public function setCursoEspecializado(?CursoEspecializado $curso_especializado): self
    {
        $this->curso_especializado = $curso_especializado;

        return $this;
    }

    public function getTallaCamisa(): ?TallaCamisa
    {
        return $this->talla_camisa;
    }

    public function setTallaCamisa(?TallaCamisa $talla_camisa): self
    {
        $this->talla_camisa = $talla_camisa;

        return $this;
    }

    public function getTallaPantalon(): ?TallaPantalon
    {
        return $this->talla_pantalon;
    }

    public function setTallaPantalon(?TallaPantalon $talla_pantalon): self
    {
        $this->talla_pantalon = $talla_pantalon;

        return $this;
    }

    public function getTallaCalzado(): ?TallaCalzado
    {

src/Entity/Prestamo.php
<?php

namespace App\Entity;

use App\Repository\PrestamoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrestamoRepository::class)]
class Prestamo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $monto = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_prestamo = null;

    #[ORM\ManyToOne(inversedBy: 'prestamos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Personal $personal = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $responsable = null;

    #[ORM\Column]
    private ?bool $estado = null;

    #[ORM\OneToMany(mappedBy: 'prestamo', targetEntity: AbonoPrestamo::class)]
    private Collection $abonoPrestamos;

    #[ORM\Column]
    private ?int $cuotas = null;

    public function __construct()
    {
        $this->abonoPrestamos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonto(): ?int
    {
        return $this->monto;
    }

    public function setMonto(int $monto): static
    {
        $this->monto = $monto;

        return $this;
    }

    public function getFechaPrestamo(): ?\DateTimeInterface
    {
        return $this->fecha_prestamo;
    }

    public function setFechaPrestamo(\DateTimeInterface $fecha_prestamo): static
    {
        $this->fecha_prestamo = $fecha_prestamo;

        return $this;
    }

    public function getPersonal(): ?Personal
    {
        return $this->personal;
    }

    public function setPersonal(?Personal $personal): static
    {
        $this->personal = $personal;

        return $this;
    }

    public function getResponsable(): ?User
    {
        return $this->responsable;
    }

    public function setResponsable(?User $responsable): static
    {
        $this->responsable = $responsable;

        return $this;
    }

    public function isEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(bool $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    /**
     * @return Collection<int, AbonoPrestamo>
     */
    public function getAbonoPrestamos(): Collection
    {
        return $this->abonoPrestamos;
    }

    public function addAbonoPrestamo(AbonoPrestamo $abonoPrestamo): static
    {
        if (!$this->abonoPrestamos->contains($abonoPrestamo)) {
            $this->abonoPrestamos->add($abonoPrestamo);
            $abonoPrestamo->setPrestamo($this);
        }

        return $this;
    }

    public function removeAbonoPrestamo(AbonoPrestamo $abonoPrestamo): static
    {
        if ($this->abonoPrestamos->removeElement($abonoPrestamo)) {
            // set the owning side to null (unless already changed)
            if ($abonoPrestamo->getPrestamo() === $this) {
                $abonoPrestamo->setPrestamo(null);
            }
        }

        return $this;
    }

    public function getCuotas(): ?int
    {
        return $this->cuotas;
    }

    public function setCuotas(int $cuotas): static
    {
        $this->cuotas = $cuotas;

        return $this;
    }
}

src/Form/PersonalType.php
<?php

namespace App\Form;

use App\Entity\Personal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('identificacion')
            ->add('lugar_expedicion')
            ->add('nombre')
            ->add('apellido')
            ->add('numero_cuenta')
            ->add('salario_basico')
            ->add('bono')
            ->add('direccion')
            ->add('telefono')
            ->add('correo_electronico')
            ->add('celular')
            ->add('f_nacimiento')
            ->add('f_ingreso')
            ->add('f_examen_ingreso')
            ->add('sexo')
            ->add('tipo_nomina')
            ->add('afp')
            ->add('eps')
            ->add('afc')
            ->add('tipo_cuenta')
            ->add('talla_uniforme')
            ->add('talla_botas')
            ->add('cargo')
            ->add('talla_guantes')
            ->add('curso_especializado')
            ->add('talla_camisa')
            ->add('talla_pantalon')
            ->add('talla_calzado')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Personal::class,
        ]);
    }
}

templates/personal/_delete_form.html.twig
<form method="post" action="{{ path('personal_delete', {'slug': personal.slug}) }}" id="deletePersonalForm">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personal.id) }}">
    <button class="btn btn-danger mt-3 " type="button" id="delete-personal" >Borrar personal</button>
</form>

templates/personal/_personal.buttons.html.twig
<div class="dropdown">
    <a class="btn btn-primary dropdown-toggle w-100" href="#" role="button" id="dropdownMenuLink"
       data-bs-toggle="dropdown" aria-expanded="false">
        Acciones
    </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        {% if empleado.activo == 1 %}
            <li>
                <a class="dropdown-item" href="{{ path('personal_deactivate', {'slug': empleado.slug}) }}">Desactivar</a>
            </li>
        {% else %}
            <li>
                <a class="dropdown-item" href="{{ path('personal_activate', {'slug': empleado.slug}) }}">Activar</a>
            </li>
        {% endif %}
        <li>
            <a class="dropdown-item" href="{{ path('personal_edit', {'slug': empleado.slug}) }}">Editar</a>
        </li>
    </ul>
</div>

templates/personal/_prestamo.form.html.twig
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-vertical" method="post" {# data-contrato-slug="{{ contrato.slug }}" #} id="updatePrestamoPersonalForm" data-parsley-validate
                          action="{{ path('prestamo_personal_update', {'id':  id }) }}">
                        <input type="hidden" name="action" id="action" value="{{ action }}">
                        <div class="form-body">
                            {% if action == 'insert' %}
                                <div class="row mb-3">
                                    <div class="col-12 form-group">
                                        <label for="personal_id2" class="form-label">Personal</label>
                                        <select class="form-select select2-personal" style="width: 100%" name="personal_id" id="personal_id" required aria-label="Default select example">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                </div>
                            {% else %}
                                <div class="row mb-3">
                                    <div class="col-12 form-group">
                                        <input type="hidden" name="personal_id" value="{{ prestamo.personal.id }}" id="personal_id_edit">
                                        <label for="personal_name" class="form-label">Personal</label>
                                        <input class="form-control" id="personal_name" value="{{ prestamo.personal.nombre~' '~prestamo.personal.apellido }}" readonly>
                                    </div>
                                </div>
                            {% endif %}
                            <div class="row mb-3">
                                <div class="col-12 form-group">
                                    <label for="fecha_prestamo" class="form-label">Fecha préstamo</label>
                                    <input type="date" class="form-control" name="fecha_prestamo" id="fecha_prestamo" value="{{ prestamo.fechaPrestamo is defined ? prestamo.fechaPrestamo|date('Y-m-d') : '' }}" data-parsley-required="true" required>
                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-12 form-group">
                                    <label for="monto" class="form-label">Monto préstamo</label>
                                    <div class="input-group ">
                                        <span class="input-group-text">$</span>
                                        <input type="text" class="form-control" name="monto" id="monto" value="{{ prestamo.monto ?? '' }}" data-parsley-required="true" required>
                                    </div>

                                </div>
                            </div>
                            <div class="row ">
                                <div class="col-12 form-group">
                                    <label for="cuotas" class="form-label">Número de cuotas</label>
                                    <input type="text" class="form-control" name="cuotas" value="{{ prestamo.cuotas ?? '' }}" data-parsley-required="false" id="cuotas">

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 d-flex justify-content-end mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">Guardar</button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reiniciar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/personal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modificar Personal{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('personal') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('personal') }}
{% endblock %}
{% block content %}
    <h2 class="ps-3">Modificar Personal</h2>

    {{ include('personal/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('personal_index') }}">Volver a la lista</a>
        </div>
    </div>

    {#{{ include('personal/_delete_form.html.twig') }}#}
{% endblock %}

templates/personal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista de Personal{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('personal-list') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('personal-list') }}
{% endblock %}
{% block content %}
    <h2>Lista de Personal</h2>
    <div class="row my-3">
        <div class="offset-8 col-2">
            <a class="btn btn-primary w-100" href="{{ path('personal_lista_excel') }}">Exportar a Excel</a>
        </div>
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('personal_new') }}">Crear Personal</a>
        </div>
    </div>

    <table class="table table-striped" id="personalDatatable">
        <thead>
            <tr>
                <th></th>
                <th>Nombre(s)</th>
                <th>Apellido(s)</th>
                <th>Identificación</th>
                <th>Lugar expedición</th>
                <th>F ingreso</th>
                <th>Cargo</th>
                <th>Estado</th>
                <th></th>
            </tr>
        </thead>
    </table>

{% endblock %}

templates/personal/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creación Personal{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('personal') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('personal') }}
{% endblock %}

{% block content %}
    <h2 class="ps-3">Creación de un nuevo personal</h2>

    {{ include('personal/_form.html.twig') }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('personal_index') }}">Volver a la lista</a>
        </div>
    </div>

{% endblock %}

templates/personal/prestamo_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modificar Préstamo Personal{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('sweetalert2') }}
    {{ encore_entry_link_tags('prestamo-personal') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('sweetalert2') }}
    {{ encore_entry_script_tags('prestamo-personal') }}
{% endblock %}
{% block content %}
    <h2 class="ps-3">Modificar Personal</h2>

    {{ include('personal/_prestamo.form.html.twig') }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('personal_index') }}">Volver a la lista</a>
        </div>
    </div>

    {#{{ include('personal/_delete_form.html.twig') }}#}
{% endblock %}

templates/personal/prestamo_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuarios{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('datatables') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datatables') }}
{% endblock %}

{% block content %}
    <h2>Lista de préstamos</h2>
    <div class="row my-3">
        <div class="offset-10 col-2">
            <a class="btn btn-primary w-100" href="{{ path('prestamo_personal_new') }}">Agregar préstamo</a>
        </div>
        {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
        {% endfor %}
    </div>

    <table class="table table-striped" id="prestamoPersonalDatatable">
        <thead>
        <tr>
            <th>Nombre completo</th>
            <th>Fecha del préstamo</th>
            <th>Monto</th>
            <th>Cuotas</th>
            <th>No. abonos</th>
            <th>Valor abonos</th>
            <th>Saldo</th>
            <th>Cuotas pendientes</th>
            <th class="text-center">Estado</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for prestamo in prestamos %}
            <tr>
                <td>{{ prestamo.nombre_personal }}</td>
                <td>{{ prestamo.fecha_prestamo|date("Y-m-d") }}</td>
                <td>{{ '$ ' }}{{ prestamo.monto|number_format  }}</td>
                <td >{{ prestamo.cuotas }}</td>
                <td >{{ prestamo.no_abonos }}</td>
                <td>{{ '$ ' }}{{ prestamo.valor_abonos|number_format }}</td>
                <td>{{ '$ ' }}{{ prestamo.saldo|number_format }}</td>
                <td class="text-center">{{ prestamo.cuotas_pendientes }}</td>
                <td class="text-center">
                    {% if prestamo.estado == 1 %}
                        <i class="bi bi-check-circle-fill activo"></i>
                    {% else %}
                        <i class="bi bi-x-circle-fill inactivo"></i>
                    {% endif %}
                </td>
                <td class="pe-0">
                    <div class="dropdown">
                        <a class="btn btn-primary dropdown-toggle w-100" href="#" role="button" id="dropdownMenuLink"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Acciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{{ path('prestamo_personal_edit', {'id': prestamo.id}) }}">Editar</a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/personal/prestamo_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creación Personal{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('sweetalert2') }}
    {{ encore_entry_link_tags('prestamo-personal') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('sweetalert2') }}
    {{ encore_entry_script_tags('prestamo-personal') }}
{% endblock %}

{% block content %}
    <h2 class="ps-3">Creación de un préstamo personal</h2>

    {{ include('personal/_prestamo.form.html.twig') }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('prestamo_personal_index') }}">Volver a la lista</a>
        </div>
    </div>

{% endblock %}

templates/personal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personal{% endblock %}

{% block content %}
    <h1>Personal</h1>

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personal.id }}</td>
            </tr>
            <tr>
                <th>Identificacion</th>
                <td>{{ personal.identificacion }}</td>
            </tr>
            <tr>
                <th>Lugar_expedicion</th>
                <td>{{ personal.lugarExpedicion }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ personal.nombre }}</td>
            </tr>
            <tr>
                <th>Apellido</th>
                <td>{{ personal.apellido }}</td>
            </tr>
            <tr>
                <th>Numero_cuenta</th>
                <td>{{ personal.numeroCuenta }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ personal.direccion }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ personal.telefono }}</td>
            </tr>
            <tr>
                <th>Correo_electronico</th>
                <td>{{ personal.correoElectronico }}</td>
            </tr>
            <tr>
                <th>Celular</th>
                <td>{{ personal.celular }}</td>
            </tr>
            <tr>
                <th>F_nacimiento</th>
                <td>{{ personal.fNacimiento ? personal.fNacimiento|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>F_ingreso</th>
                <td>{{ personal.fIngreso ? personal.fIngreso|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>F_examen_ingreso</th>
                <td>{{ personal.fExamenIngreso ? personal.fExamenIngreso|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('personal_index') }}">back to list</a>

    <a href="{{ path('personal_edit', {'slug': personal.slug.toRfc4122()}) }}">edit</a>

    {{ include('personal/_delete_form.html.twig') }}
{% endblock %}