src/Entity/Afc.php
<?php

namespace App\Entity;

use App\Repository\AfcRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AfcRepository::class)]
class Afc
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contacto = null;

    #[ORM\Column(nullable: true)]
    private ?string $telefono = null;

    #[ORM\Column(nullable: true)]
    private ?int $extension = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_creacion = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_actualizacion = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(nullable: true)]
    private ?string $celular = null;

    #[ORM\OneToMany(mappedBy: 'afc', targetEntity: Personal::class)]
    private Collection $personals;

    public function __construct()
    {
        $this->personals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getContacto(): ?string
    {
        return $this->contacto;
    }

    public function setContacto(?string $contacto): self
    {
        $this->contacto = $contacto;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getExtension(): ?int
    {
        return $this->extension;
    }

    public function setExtension(?int $extension): self
    {

        $this->extension = $extension !== 0 ? $extension : null;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(?\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getFechaActualizacion(): ?\DateTimeInterface
    {
        return $this->fecha_actualizacion;
    }

    public function setFechaActualizacion(?\DateTimeInterface $fecha_actualizacion): self
    {
        $this->fecha_actualizacion = $fecha_actualizacion;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCelular(): ?string
    {
        return $this->celular;
    }

    public function setCelular(?string $celular): self
    {
        $this->celular = $celular;

        return $this;
    }

    /**
     * @return Collection<int, Personal>
     */
    public function getPersonals(): Collection
    {
        return $this->personals;
    }

    public function addPersonal(Personal $personal): self
    {
        if (!$this->personals->contains($personal)) {
            $this->personals->add($personal);
            $personal->setAfc($this);
        }

        return $this;
    }

    public function removePersonal(Personal $personal): self
    {
        if ($this->personals->removeElement($personal)) {
            // set the owning side to null (unless already changed)
            if ($personal->getAfc() === $this) {
                $personal->setAfc(null);
            }
        }

        return $this;
    }
}

src/Controller/NominaController.php
<?php

namespace App\Controller;

use App\Entity\NovedadNomina;
use App\Entity\ParametroNomina;
use App\Entity\TipoNovedadNomina;
use App\Repository\NovedadNominaRepository;
use App\Repository\ParametroNominaRepository;
use App\Repository\PersonalRepository;
use App\Repository\TipoNovedadNominaRepository;
use App\Service\DataTablesServerSide;
use Carbon\Carbon;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/nomina')]
class NominaController extends AbstractController
{
    #[Route('/', name: 'app_nomina')]
    public function index(): Response
    {
        return $this->render('nomina/index.html.twig', [
            'controller_name' => 'NominaController',
        ]);
    }

    #[Route('/parametros', name: 'parametros_nomina')]
    public function parametros(ParametroNominaRepository $parametroNominaRepository): Response
    {
        return $this->render('nomina/parametros.html.twig', [
            'parametros' => $parametroNominaRepository->findAll(),
        ]);
    }

    #[Route('/parametro/nuevo', name: 'parametro_new', methods: ['GET', 'POST'])]
    public function parametro_new(Request $request): Response
    {
        return $this->render('nomina/new_parametro_nomina.html.twig', [
            'action' => 'insert',
        ]);
    }


    #[Route('/parametro/{id}/editar', name: 'parametro_edit', methods: ['GET'])]
    public function parametro_edit(Request $request, ParametroNomina $parametroNomina, ParametroNominaRepository $parametroNominaRepository): Response
    {
        return $this->render('nomina/edit_parametro_nomina.html.twig', [
            'parametroNomina' => $parametroNomina,
            'action' => 'update',
        ]);
    }

    #[Route('/parametro/{id}/actualizar', name: 'parametro_nomina_update', methods: ['POST'])]
    public function parametro_nomina_update(Request $request, int $id, ParametroNominaRepository $parametroNominaRepository, EntityManagerInterface $entityManager): Response
    {
        if ($id == 0) {
            $parametro_nomina = new ParametroNomina();
        } else {
            $parametro_nomina = $parametroNominaRepository->find($id);
        }
        $parametro_nomina->setParametro(trim($request->request->get('parametro')));
        $parametro_nomina->setValor(trim($request->request->get('valor')));
        $action = $request->request->get('action');
        if ($action == 'insert') {
            $parametro_nomina->setFechaCreacion(Carbon::today());
            $parametro_nomina->setFechaActualizacion(Carbon::today());
        } else {
            $parametro_nomina->setFechaActualizacion(Carbon::today());
        }
        $entityManager->persist($parametro_nomina);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();
        if ($action == 'insert') {
            $this->addFlash('success', 'Parámetro de nómina creado correctamente');
        } else {
            $this->addFlash('success', 'Parámetro de nómina actualizado correctamente');
        }
        return $this->redirectToRoute('parametros_nomina', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/tipos-novedad', name: 'tipos_novedad_nomina')]
    public function tipos_novedades(TipoNovedadNominaRepository $tipoNovedadNominaRepository): Response
    {
        return $this->render('nomina/tipo_novedades.html.twig', [
            'tipos_novedades' => $tipoNovedadNominaRepository->findAll(),
        ]);
    }

    #[Route('/tipo-novedad/nuevo', name: 'tipo_novedad_nomina_new', methods: ['GET', 'POST'])]
    public function tipo_novedad_new(Request $request): Response
    {
        return $this->render('nomina/new_tipo_novedad_nomina.html.twig', [
            'action' => 'insert',
        ]);
    }


    #[Route('/tipo-novedad/{id}/editar', name: 'tipo_novedad_nomina_edit', methods: ['GET'])]
    public function tipo_novedad_edit(Request $request, TipoNovedadNomina $tipoNovedadNomina, TipoNovedadNominaRepository $tipoNovedadNominaRepository): Response
    {
        return $this->render('nomina/edit_tipo_novedad_nomina.html.twig', [
            'tipoNovedadNomina' => $tipoNovedadNomina,
            'action' => 'update',
        ]);
    }

    #[Route('/tipo-novedad/{id}/actualizar', name: 'tipo_novedad_nomina_update', methods: ['POST'])]
    public function tipo_novedad_update(Request $request, int $id, TipoNovedadNominaRepository $tipoNovedadNominaRepository, EntityManagerInterface $entityManager): Response
    {
        if ($id == 0) {
            $tipo_novedad_nomina = new TipoNovedadNomina();
            $tipo_novedad_nomina->setFechaCreacion(Carbon::today());
        } else {
            $tipo_novedad_nomina = $tipoNovedadNominaRepository->find($id);
        }
        $tipo_novedad_nomina->setUser($this->getUser());
        $tipo_novedad_nomina->setFechaActualizacion(Carbon::today());
        $tipo_novedad_nomina->setDescripcion(trim($request->request->get('descripcion')));
        $action = $request->request->get('action');
        $entityManager->persist($tipo_novedad_nomina);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();
        if ($action == 'insert') {
            $this->addFlash('success', 'Tipo novedad de nómina creado correctamente');
        } else {
            $this->addFlash('success', 'Tipo novedad de nómina actualizado correctamente');
        }
        return $this->redirectToRoute('tipos_novedad_nomina', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/novedades', name: 'novedades_nomina')]
    public function novedades_nomina(NovedadNominaRepository $novedadNominaRepository): Response
    {

        return $this->render('nomina/novedades_nomina.html.twig', [

        ]);
    }

    #[Route('/novedades/lista', name: 'lista_novedades_nomina', methods: ['POST'])]
    public function lista_novedades_nomina(NovedadNominaRepository $novedadNominaRepository): JsonResponse
    {
        $columns = array(
            array('db' => 'p.nombre', 'dt' => 'personal'),
            array('db' => 'tnn.descripcion', 'dt' => 'tipo_novedad'),
            array('db' => 'nn.fecha_inicio', 'dt' => 'f_inicio'),
            array('db' => 'nn.fecha_fin', 'dt' => 'f_fin'),
            array('db' => 'nn.observaciones', 'dt' => 'observaciones'),
            array('db' => 'nn.fecha_creacion', 'dt' => 'f_creacion'),
            array('db' => 'nn.fecha_actualizacion', 'dt' => 'f_actualizacion'),
        );
        $bindings = array();
        $limit = DataTablesServerSide::limit($_POST, $columns);
        $order = DataTablesServerSide::order($_POST, $columns);
        $where = DataTablesServerSide::filter($_POST, $columns, $bindings);

        $totalNovedadesNomina = $novedadNominaRepository->getTotalTablaNovedadesNomina($where, $bindings);
        $novedades_nomina = $novedadNominaRepository->getTablaNovedadesNomina($limit, $order, $where, $bindings);
        $return = [
            "draw"            => isset ( $_POST['draw'] ) ?
                intval( $_POST['draw'] ) :
                0,
            'recordsTotal' => $totalNovedadesNomina,
            'recordsFiltered' => $totalNovedadesNomina,
            'data' => $novedades_nomina
        ];

        return $this->json($return);
    }


    #[Route('/novedad/nueva', name: 'novedad_nomina_new', methods: ['GET', 'POST'])]
    public function novedad_nomina_new(Request $request, TipoNovedadNominaRepository $tipoNovedadNominaRepository): Response
    {
        $tiposNovedadNomina = $tipoNovedadNominaRepository->findBy([], ['descripcion' => 'ASC']);
        return $this->render('nomina/new_novedad_nomina.html.twig', [
            'action' => 'insert',
            'tiposNovedadNomina' => $tiposNovedadNomina
        ]);
    }


    #[Route('/novedad/{id}/editar', name: 'novedad_nomina_edit', methods: ['GET'])]
    public function novedad_nomina_edit(Request $request, NovedadNomina $novedadNomina, NovedadNominaRepository $novedadNominaRepository, TipoNovedadNominaRepository $tipoNovedadNominaRepository): Response
    {
        $tiposNovedadNomina = $tipoNovedadNominaRepository->findBy([], ['descripcion' => 'ASC']);
        return $this->render('nomina/edit_novedad_nomina.html.twig', [
            'novedadNomina' => $novedadNomina->toArray(),
            'action' => 'update',
            'tiposNovedadNomina' => $tiposNovedadNomina
        ]);
    }

    #[Route('/novedad/{id}/guardar', name: 'novedad_nomina_update', methods: ['POST'])]
    public function novedad_nomina_update(Request $request, int $id, PersonalRepository $personalRepository, TipoNovedadNominaRepository $tipoNovedadNominaRepository, NovedadNominaRepository $novedadNominaRepository, EntityManagerInterface $entityManager): Response
    {
        if ($id == 0) {
            $novedad_nomina = new NovedadNomina();
            $novedad_nomina->setFechaCreacion(Carbon::today());
            $novedad_nomina->setFechaActualizacion(Carbon::today());
        } else {
            $novedad_nomina = $novedadNominaRepository->find($id);
        }
        $personal = $personalRepository->find(trim($request->request->get('personal_id')));
        $tipo_novedad = $tipoNovedadNominaRepository->find(trim($request->request->get('tipo_novedad_id')));
        $novedad_nomina->setTipoNovedad($tipo_novedad);
        $novedad_nomina->setPersonal($personal);
        $novedad_nomina->setFechaInicio(Carbon::parse(trim($request->request->get('fecha_inicio'))));
        $novedad_nomina->setFechaFin(Carbon::parse(trim($request->request->get('fecha_fin'))));
        $novedad_nomina->setActiva(trim($request->request->get('activa')));
        $novedad_nomina->setObservaciones(trim($request->request->get('observaciones')));

templates/nomina/_form_novedad_nomina.html.twig
<div class="row">
    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-vertical" method="post" data-parsley-validate
                          action="{{ action == 'update' ? path('novedad_nomina_update', {'id':  novedadNomina.id }) :  path('novedad_nomina_update', {'id':  0 }) }}"
                    >
                        <input type="hidden" name="action" id="action" value="{{ action }}">
                        <div class="form-body">
                            <input type="hidden" name="activa" id="activa" value="{{ action == 'update' ? novedadNomina.activa : '1' }}">
                            {% if action == 'insert' %}
                                <div class="row mb-3">
                                    <div class="col-12 form-group">
                                        <label for="personal_id2" class="form-label">Personal</label>
                                        <select class="form-select select2-personal" style="width: 100%" name="personal_id" id="personal_id" required aria-label="Default select example">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                </div>
                            {% else %}
                                <div class="row mb-3">
                                    <div class="col-12 form-group">
                                        <input type="hidden" name="personal_id" value="{{ novedadNomina.personal_id }}" id="personal_id_edit">
                                        <label for="personal_name" class="form-label">Personal</label>
                                        <input class="form-control" id="personal_name" value="{{ novedadNomina.personal_nombre }}" readonly>
                                    </div>
                                </div>
                            {% endif %}
                            <div class="row mb-3">
                                <div class="col-12 form-group">
                                    <label for="tipo_novedad_id" class="form-label">Tipo Novedad Nómina</label>
                                    <select class="form-select" aria-label="Default select example"  name="tipo_novedad_id" id="tipo_novedad_id" data-parsley-required="true" required>
                                        <option value="" selected>Seleccione una opción</option>
                                        {% for tipoNovedadNomina in tiposNovedadNomina %}
                                            <option value="{{ tipoNovedadNomina.id }}" {{ novedadNomina.tipo_novedad_id is defined and novedadNomina.tipo_novedad_id == tipoNovedadNomina.id ? 'selected' : '' }}>{{ tipoNovedadNomina.descripcion }}</option>
                                        {% endfor %} %
                                    </select>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-6 form-group">
                                    <label for="fecha_inicio" class="form-label">Fecha de inicio</label>
                                    <input type="{{ novedadNomina.tipo_novedad_id is defined and (novedadNomina.tipo_novedad_id == 7 or novedadNomina.tipo_novedad_id == 7) ? 'datetime-local' : 'date' }}" class="form-control" name="fecha_inicio" id="fecha_inicio" value="{{ novedadNomina.f_inicio ?? ''}}" data-parsley-required="true" required>
                                </div>
                                <div class="col-6 form-group">
                                    <label for="fecha_fin" class="form-label">Fecha de fin</label>
                                    <input type="{{ novedadNomina.tipo_novedad_id is defined and (novedadNomina.tipo_novedad_id == 7 or novedadNomina.tipo_novedad_id == 7) ? 'datetime-local' : 'date' }}" class="form-control" name="fecha_fin" id="fecha_fin" value="{{ novedadNomina.f_fin ?? ''}}" data-parsley-required="true" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="observaciones">Observaciones</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="observaciones" name="observaciones"
                                                   value="{{ novedadNomina.observaciones ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 d-flex justify-content-end mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">Guardar</button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reiniciar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/nomina/_form_parametro_nomina.html.twig
<div class="row">
    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-vertical" method="post" data-parsley-validate
                          action="{% if parametroNomina.id is defined %}{{ path('parametro_nomina_update', {'id':  parametroNomina.id }) }}{% else %}{{ path('parametro_nomina_update', {'id':  0 }) }}{% endif %}"
                    >
                        <input type="hidden" name="action" id="action" value="{{ action }}">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="parametro">Parámetro</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control"
                                                   id="parametro" name="parametro" required
                                                   data-parsley-required="true"
                                                   value="{{ parametroNomina.parametro ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="valor">Valor</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control"
                                                   id="valor" name="valor"
                                                   data-parsley-required="true"
                                                   value="{{ parametroNomina.valor ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 d-flex justify-content-end mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">Guardar</button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reiniciar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/nomina/_form_tipo_novedad_nomina.html.twig
<div class="row">
    <div class="col-md-6 col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-vertical" method="post" data-parsley-validate
                          action="{% if tipoNovedadNomina.id is defined %}{{ path('tipo_novedad_nomina_update', {'id':  tipoNovedadNomina.id }) }}{% else %}{{ path('tipo_novedad_nomina_update', {'id':  0 }) }}{% endif %}"
                    >
                        <input type="hidden" name="action" id="action" value="{{ action }}">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="descripcion">Descripción</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="descripcion" name="descripcion" required data-parsley-required="true"
                                                   value="{{ tipoNovedadNomina.descripcion ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 d-flex justify-content-end mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">Guardar</button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reiniciar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/nomina/_novedades_nomina.buttons.html.twig
<div class="dropdown">
    <a class="btn btn-primary dropdown-toggle w-100" href="#" role="button" id="dropdownMenuLink"
       data-bs-toggle="dropdown" aria-expanded="false">
        Acciones
    </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li>
            <a class="dropdown-item" href="{{ path('novedad_nomina_edit', {'id': novedadNomina.id}) }}">Editar</a>
        </li>
        {#<li>
            <a class="dropdown-item" href="{{ path('contrato_personal', {'slug': contrato.slug}) }}">Personal</a>
        </li>
        <li>
            <a class="dropdown-item" href="{{ path('contrato_renovar', {'slug': contrato.slug}) }}">Renovar</a>
        </li>#}
    </ul>
</div>

templates/nomina/edit_novedad_nomina.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar tipo novedad de nómina{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('novedades-nomina') }}
    {{ encore_entry_link_tags('sweetalert2') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_link_tags('novedades-nomina') }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('sweetalert2') }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h2 class="ps-4">Editar tipo novedad de nómina</h2>
        </div>
    </div>

    {{ include('nomina/_form_novedad_nomina.html.twig', {'button_label': 'Update'}) }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('novedades_nomina') }}">Volver a la lista</a>
        </div>
    </div>

{% endblock %}

templates/nomina/edit_parametro_nomina.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar parámetro de nómina{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('sweetalert2') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('sweetalert2') }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h2 class="ps-4">Editar AFP</h2>
        </div>
    </div>

    {{ include('nomina/_form_parametro_nomina.html.twig', {'button_label': 'Update'}) }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('parametros_nomina') }}">Volver a la lista</a>
        </div>
    </div>
    {% if is_granted('ROLE_ADMINISTRADOR') %}
        {{ include('afp/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}

templates/nomina/new_parametro_nomina.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crear parámetro nómina{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}

{% endblock %}

{% block content %}
    <h2 class="ps-3">Crear parámetro nómina</h2>

    {{ include('nomina/_form_parametro_nomina.html.twig') }}

    <div class="row my-3">
        <div class="offset-4 col-2">
            <a class="btn btn-primary w-100" href="{{ path('parametros_nomina') }}">Volver a la lista</a>
        </div>
    </div>

{% endblock %}

templates/nomina/parametros.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parámetros Nómina{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('datatables') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datatables') }}
{% endblock %}

{% block content %}
    <h2>Parámetros Nómina</h2>
    <div class="row my-3">
        <div class="offset-10 col-2">
            <a class="btn btn-primary w-100" href="{{ path('parametro_new') }}">Crear parámetro</a>
        </div>
    </div>

    <table class="table" id="parametrosNominaDatatable">
        <thead>
        <tr>
            <th>Id</th>
            <th>Parámetro</th>
            <th>Valor</th>
            <th>Fecha creación</th>
            <th>Fecha actualización</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for parametro in parametros %}
            <tr>
                <td>{{ parametro.id }}</td>
                <td>{{ parametro.parametro }}</td>
                <td>{{ parametro.valor }}</td>
                <td>{{ parametro.fechaCreacion ? parametro.fechaCreacion|date('d-m-Y') : '' }}</td>
                <td>{{ parametro.fechaActualizacion ? parametro.fechaActualizacion|date('d-m-Y') : '' }}</td>
                <td class="pe-0">
                    <div class="dropdown">
                        <a class="btn btn-primary dropdown-toggle w-100" href="#" role="button" id="dropdownMenuLink"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Acciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{{ path('parametro_edit', {'id': parametro.id}) }}">Editar</a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9" class="text-center">No hay registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/nomina/tipo_novedades.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parámetros Nómina{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('datatables') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('datatables') }}
{% endblock %}

{% block content %}
    <h2>Tipo novedad Nómina</h2>
    <div class="row my-3">
        <div class="offset-10 col-2">
            <a class="btn btn-primary w-100" href="{{ path('tipo_novedad_nomina_new') }}">Crear parámetro</a>
        </div>
    </div>

    <table class="table table-striped" id="tiposNovedadesNominaDatatable">
        <thead>
        <tr>
            <th>Id</th>
            <th>Descripción</th>
            <th>Modificado por</th>
            <th>Fecha creación</th>
            <th>Fecha actualización</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for tipo_novedad in tipos_novedades %}
            <tr>
                <td>{{ tipo_novedad.id }}</td>
                <td>{{ tipo_novedad.descripcion }}</td>
                <td>{{ tipo_novedad.user.nombre~' '~ tipo_novedad.user.apellido}}</td>
                <td>{{ tipo_novedad.fechaCreacion ? tipo_novedad.fechaCreacion|date('d-m-Y') : '' }}</td>
                <td>{{ tipo_novedad.fechaActualizacion ? tipo_novedad.fechaActualizacion|date('d-m-Y') : '' }}</td>
                <td class="pe-0">
                    <div class="dropdown">
                        <a class="btn btn-primary dropdown-toggle w-100" href="#" role="button" id="dropdownMenuLink"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Acciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{{ path('tipo_novedad_nomina_edit', {'id': tipo_novedad.id}) }}">Editar</a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9" class="text-center">No hay registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}