src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: ClienteRepository::class)]
class Cliente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nit = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $direccion = null;

    #[ORM\Column(nullable: true)]
    private ?string $telefono = null;

    #[ORM\Column(length: 255)]
    private ?string $contacto = null;

    #[ORM\Column(nullable: true)]
    private ?string $celular = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $correo_electronico = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $observaciones = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $f_creacion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $f_actualizacion = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'cliente', targetEntity: Contrato::class)]
    private Collection $contratos;

    #[ORM\Column]
    private ?bool $estado = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telefono2 = null;

    #[ORM\Column(type: 'uuid', nullable: true)]
    private ?Uuid $slug;

    public function __construct()
    {
        $this->contratos = new ArrayCollection();
        $this->slug = Uuid::v6();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNit(): ?string
    {
        return $this->nit;
    }

    public function setNit(string $nit): self
    {
        $this->nit = $nit;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getContacto(): ?string
    {
        return $this->contacto;
    }

    public function setContacto(string $contacto): self
    {
        $this->contacto = $contacto;

        return $this;
    }

    public function getCelular(): ?string
    {
        return $this->celular;
    }

    public function setCelular(?string $celular): self
    {
        $this->celular = $celular;

        return $this;
    }

    public function getCorreoElectronico(): ?string
    {
        return $this->correo_electronico;
    }

    public function setCorreoElectronico(?string $correo_electronico): self
    {
        $this->correo_electronico = $correo_electronico;

        return $this;
    }

    public function getObservaciones(): ?string
    {
        return $this->observaciones;
    }

    public function setObservaciones(?string $observaciones): self
    {
        $this->observaciones = $observaciones;

        return $this;
    }

    public function getFCreacion(): ?\DateTimeInterface
    {
        return $this->f_creacion;
    }

    public function setFCreacion(\DateTimeInterface $f_creacion): self
    {
        $this->f_creacion = $f_creacion;

        return $this;
    }

    public function getFActualizacion(): ?\DateTimeInterface
    {
        return $this->f_actualizacion;
    }

    public function setFActualizacion(\DateTimeInterface $f_actualizacion): self
    {
        $this->f_actualizacion = $f_actualizacion;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Contrato>
     */
    public function getContratos(): Collection
    {
        return $this->contratos;
    }

    public function addContrato(Contrato $contrato): self
    {
        if (!$this->contratos->contains($contrato)) {
            $this->contratos->add($contrato);
            $contrato->setCliente($this);
        }

        return $this;
    }

    public function removeContrato(Contrato $contrato): self
    {
        if ($this->contratos->removeElement($contrato)) {
            // set the owning side to null (unless already changed)
            if ($contrato->getCliente() === $this) {
                $contrato->setCliente(null);
            }
        }

        return $this;
    }

    public function isEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(bool $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getTelefono2(): ?string
    {
        return $this->telefono2;
    }

    public function setTelefono2(?string $telefono2): self
    {
        $this->telefono2 = $telefono2;

        return $this;
    }

    public function getSlug(): ?Uuid
    {
        return $this->slug;
    }

    public function setSlug(?Uuid $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function toArray()
    {
        return [
            'id' => $this->getId(),
            'nit' => $this->getNit(),
            'nombre' => $this->getNombre(),
            'direccion' => $this->getDireccion(),
            'telefono' => $this->getTelefono(),
            'contacto' => $this->getContacto(),
            'celular' => $this->getCelular(),
            'correo_electronico' => $this->getCorreoElectronico(),
            'observaciones' => $this->getObservaciones(),
            'f_creacion' => $this->getFCreacion()->format('d/m/Y'),
            'f_actualizacion' => $this->getFActualizacion()->format('d/m/Y'),
            'modificado_por' => $this->getUser()->getNombre().' '.$this->getUser()->getApellido(),
            'estado' => $this->isEstado(),
            'telefono2' => $this->getTelefono2(),
            'slug' => $this->getSlug()->toRfc4122()
        ];
    }
    public function toArrayExport()
    {
        return [
            'Id' => $this->getId(),
            'Nit' => $this->getNit(),
            'Nombre' => $this->getNombre(),
            'Dirección' => $this->getDireccion(),
            'Teléfono 1' => $this->getTelefono(),
            'Contacto' => $this->getContacto(),
            'Celular' => $this->getCelular(),
            'Correo electrónico' => $this->getCorreoElectronico(),
            'Fecha creación' => $this->getFCreacion()->format('d/m/Y'),
            'Fecha actualización' => $this->getFActualizacion()->format('d/m/Y'),
            'Estado' => $this->isEstado() ? 'Activo' : 'Inactivo',
            'Teléfono 2' => $this->getTelefono2(),
            'Observaciones' => $this->getObservaciones()
        ];
    }
}

src/Form/ClienteType.php
<?php

namespace App\Form;

use App\Entity\Cliente;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClienteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ceco')
            ->add('nit')
            ->add('nombre')
            ->add('direccion')
            ->add('telefono')
            ->add('administrador')
            ->add('celular')
            ->add('correo_electronico')
            ->add('observaciones')
            ->add('f_creacion')
            ->add('f_actualizacion')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cliente::class,
        ]);
    }
}

src/Controller/ClienteController.php
<?php

namespace App\Controller;

use App\Entity\Cliente;
use App\Form\ClienteType;
use App\Repository\ClienteRepository;
use App\Service\GenerarXls;
use Carbon\Carbon;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Uid\Uuid;

#[Route('/cliente')]
class ClienteController extends AbstractController
{
    #[Route('/', name: 'cliente_index', methods: ['GET'])]
    public function index(ClienteRepository $clienteRepository): Response
    {
        return $this->render('cliente/index.html.twig', [
            'clientes' => $clienteRepository->findAll(),
        ]);
    }

    #[Route('/nuevo', name: 'cliente_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ClienteRepository $clienteRepository): Response
    {
        $slug = Uuid::v6();
        return $this->render('cliente/new.html.twig', [
            'action' => 'insert',
            'slug' => $slug,
        ]);
    }
    #[Route('/lista', name: 'cliente_lista', methods: ['POST'])]
    public function lista(ClienteRepository $clienteRepository): JsonResponse
    {
        $clientes = $clienteRepository->findAll();
        $clientesToArray = [];
        foreach ($clientes as $key => $cliente) {
            $clientesToArray[$key] = $cliente->toArray();
            $clientesToArray[$key]['estado_show'] = $clientesToArray[$key]['estado'] == true ? '<i class="bi bi-check-circle-fill activo"></i>' : '<i class="bi bi-x-circle-fill inactivo"></i>';
            //$clientesToArray[$key]['actions'] = $this->renderView('cliente/_cliente.buttons.html.twig', ['cliente' => $clientesToArray[$key]]);
        }

        //To array
//        $personalsToArray = array_map(function ($personal) {
//            /** @var Personal $personal */
//            $arr = $personal->toArray();
//            return $arr;
//        }, $personals);
        $return = [
            'draw' => 0,
            'recordsTotal' => count($clientesToArray),
            'recordsFiltered' => count($clientesToArray),
            'data' => $clientesToArray
        ];

        return $this->json($return);
    }
    #[Route('/exportar', name: 'cliente_lista_excel')]
    public function cliente_lista_excel(ClienteRepository $clienteRepository, GenerarXls $generarXls): BinaryFileResponse
    {
        $clientes = $clienteRepository->findBy([], ['nombre' => 'ASC']);
        //To array
        $clientesToArray = array_map(function ($cliente) {
            /** @var Cliente $cliente */
            $arr = $cliente->toArrayExport();
            return $arr;
        }, $clientes);
        $file = $generarXls->crearXls($clientesToArray, 'Lista de Clientes');

        // send the file contents and force the browser to download it
        return $this->file($file);
    }
    #[Route('/{slug}/editar', name: 'cliente_edit', methods: ['GET'])]
    public function edit(Request $request, string $slug, ClienteRepository $clienteRepository): Response
    {
        $cliente = $clienteRepository->findOneBy(['slug' => Uuid::fromString($slug) ]);
        //dd($cliente->getSlug()->toRfc4122());

        return $this->render('cliente/edit.html.twig', [
            'cliente' => $cliente->toArray(),
            'action' => 'update',
        ]);
    }

    #[Route('/{slug}/actualizar', name: 'cliente_update', methods: ['POST'])]
    public function update(Request $request, string $slug, EntityManagerInterface $entityManager, ClienteRepository $clienteRepository): Response
    {
        $user = $this->getUser();
        $action = $request->request->get('action');
        $cliente = $clienteRepository->findOneBy(['slug' => Uuid::fromString($slug) ]);
        if (!$cliente){
            $cliente = new Cliente();
            $cliente->setSlug(Uuid::fromString($slug));
        }
        $cliente->setEstado(trim($request->request->get('estado', false)));
        $cliente->setNit(trim($request->request->get('nit', '')));
        $cliente->setNombre(trim($request->request->get('nombre', '')));
        $cliente->setDireccion(trim($request->request->get('direccion', '')));
        $cliente->setTelefono(trim($request->request->get('telefono', '')));
        $cliente->setTelefono2(trim($request->request->get('telefono2', '')));
        $cliente->setContacto(trim($request->request->get('contacto', '')));
        $cliente->setCelular(trim($request->request->get('celular', '')));
        $cliente->setCorreoElectronico(trim($request->request->get('correo_electronico', '')));
        $cliente->setObservaciones(trim($request->request->get('observaciones', '')));
        $cliente->setFActualizacion(Carbon::now());
        $cliente->setUser($user);
        $entityManager->persist($cliente);
        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();

        if ($action == 'insert') {
            $this->addFlash('success', 'Cliente creado correctamente');
        } else {
            $this->addFlash('success', 'Cliente actualizado correctamente');
        }

        //$this->addFlash('error', ' Error al actualizar el Cliente');
        return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);

    }

    #[Route('/{slug}/activar', name: 'cliente_activate', methods: ['GET'])]
    public function activate(Request $request, string $slug, EntityManagerInterface $entityManager, ClienteRepository $clienteRepository): Response
    {
        $cliente = $clienteRepository->findOneBy(['slug' => Uuid::fromString($slug) ]);
        $cliente->setEstado(true);
        $entityManager->persist($cliente);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();

        $this->addFlash('success', 'Cliente activado correctamente');
        //$this->addFlash('error', ' Error al actualizar el Cliente');
        return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);

    }
    #[Route('/{slug}/desactivar', name: 'cliente_deactivate', methods: ['GET'])]
    public function deactivate(Request $request, string $slug, EntityManagerInterface $entityManager, ClienteRepository $clienteRepository): Response
    {
        $cliente = $clienteRepository->findOneBy(['slug' => Uuid::fromString($slug) ]);
        $cliente->setEstado(false);
        $entityManager->persist($cliente);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();

        $this->addFlash('success', 'Cliente desactivado correctamente');
        //$this->addFlash('error', ' Error al actualizar el Cliente');
        return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);

    }

    #[Route('/{slug}', name: 'cliente_show', methods: ['GET'])]
    public function show(string $slug, ClienteRepository $clienteRepository): Response
    {
        $cliente = $clienteRepository->findOneBy(['slug' => Uuid::fromString($slug) ]);
        return $this->render('cliente/show.html.twig', [
            'cliente' => $cliente,
        ]);
    }

    #[Route('/{slug}/borrar', name: 'cliente_delete', methods: ['POST'])]
    public function delete(Request $request, string $slug, ClienteRepository $clienteRepository): Response
    {
        $cliente = $clienteRepository->findOneBy(['slug' => Uuid::fromString($slug) ]);
        if ($this->isCsrfTokenValid('delete'.$cliente->getId(), $request->request->get('_token'))) {
            $clienteRepository->remove($cliente, true);
        }
        return $this->redirectToRoute('cliente_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cliente/_cliente.buttons.html.twig
<div class="dropdown">
    <a class="btn btn-primary dropdown-toggle w-100" href="#" role="button" id="dropdownMenuLink"
       data-bs-toggle="dropdown" aria-expanded="false">
        Acciones
    </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        {% if cliente.estado == 1 %}
            <li>
                <a class="dropdown-item" href=" {{ path('cliente_deactivate', {'slug': cliente.slug}) }} ">Desactivar</a>
            </li>
        {% else %}
            <li>
                <a class="dropdown-item" href=" {{ path('cliente_activate', {'slug': cliente.slug}) }} ">Activar</a>
            </li>
        {% endif %}
        <li>
            <a class="dropdown-item" href="{{ path('cliente_edit', {'slug': cliente.slug}) }}">Editar</a>
        </li>
    </ul>
</div>

templates/cliente/_delete_form.html.twig
<form method="post" action="{{ path('cliente_delete', {'slug': cliente.slug}) }}" id="deleteClienteForm">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cliente.id) }}">
    <button class="btn btn-danger mt-3" type="button" id="delete-cliente">Delete</button>
</form>

templates/cliente/_form.html.twig
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <form class="form form-vertical" method="post" data-parsley-validate
                          action="{{ cliente.slug is defined ? path('cliente_update', {'slug':  cliente.slug }) : path('cliente_update', {'slug':  slug }) }}">
                        <input type="hidden" name="action" id="action" value="{{ action }}">
                        <div class="form-body">
                            <div class="row">
                                <div class="col-12 mb-3">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" name="estado" value="1" {{ cliente is defined and cliente.estado == true ? 'checked' : '' }} role="switch"
                                               id="estado">
                                        <label class="form-check-label" for="estado">Cliente activo</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                {% if action == 'insert' %}
                                    <div class="col-2">
                                        <div class="form-group">
                                            <label for="numero">Número nit</label>
                                            <div class="position-relative has-validation">
                                                <input type="text" class="form-control" onkeyup="nitClientes()" id="numero" name="numero" value="" >
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="col-{{ action == 'insert' ? '2' : '4' }}">
                                    <div class="form-group">
                                        <label for="nit">Nit cliente</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="nit" name="nit" required data-parsley-required="true"
                                                   value="{{ cliente.nit ?? '' }}" {{ action == 'update' ? 'readonly' : '' }}>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-8">
                                    <div class="form-group">
                                        <label for="nombre">Nombre del cliente</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="nombre" name="nombre" required data-parsley-required="true" value="{{ cliente.nombre ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="telefono">Teléfono cliente</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="telefono" name="telefono" required data-parsley-required="true" value="{{ cliente.telefono ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="telefono2">Teléfono cliente 2</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="telefono2" name="telefono2" value="{{ cliente.telefono2 ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-8">
                                    <div class="form-group">
                                        <label for="direccion">Dirección del cliente</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="direccion" name="direccion" required data-parsley-required="true" value="{{ cliente.direccion ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-5">
                                    <div class="form-group">
                                        <label for="contacto">Contacto cliente</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="contacto" name="contacto" required data-parsley-required="true" value="{{ cliente.contacto ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-5">
                                    <div class="form-group">
                                        <label for="correo_electronico">Correo electrónico</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="correo_electronico" name="correo_electronico" required data-parsley-required="true" value="{{ cliente.correo_electronico ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="celular">Celular</label>
                                        <div class="position-relative has-validation">
                                            <input type="text" class="form-control" id="celular" name="celular" value="{{ cliente.celular ?? '' }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="observaciones">Observaciones</label>
                                        <div class="position-relative has-validation">
                                            <textarea class="form-control" name="observaciones" id="observaciones" rows="3">{{ cliente.observaciones ?? '' }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                             <div class="row">
                                <div class="col-12 d-flex justify-content-end mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">Guardar</button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reiniciar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/cliente/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cliente{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('sweetalert2') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('sweetalert2') }}
{% endblock %}

{% block content %}
    <h2 class="ps-3">Modificar Cliente</h2>

    {{ include('cliente/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('cliente_index') }}">Volver a la lista</a>
        </div>
    </div>

    {#{{ include('cliente/_delete_form.html.twig') }}#}
{% endblock %}

templates/cliente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cliente index{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('clientes-list') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('clientes-list') }}
{% endblock %}

{% block content %}
    <h2>Lista de clientes</h2>
    <div class="row my-3">
        <div class="offset-8 col-2">
            <a class="btn btn-primary w-100" target="_blank" href="{{ path('cliente_lista_excel') }}">Exportar a Excel</a>
        </div>
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('cliente_new') }}">Crear cliente</a>
        </div>
    </div>

    <table class="table w-100 table-striped" id="clientesDatatable">
        <thead>
            <tr>
                <th style="width: 3%"></th>
                <th style="width: 10%">Nit</th>
                <th style="width: 40%">Nombre</th>
                <th style="width: 24%">Dirección</th>
                <th style="width: 10%">Observaciones</th>
                <th style="width: 3%">Estado</th>
                <th style="width: 10%"></th>
            </tr>
        </thead>
    </table>
{% endblock %}

templates/cliente/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crear Cliente{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('sweetalert2') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('cliente') }}
    {{ encore_entry_script_tags('parsley') }}
    {{ encore_entry_script_tags('sweetalert2') }}
{% endblock %}

{% block content %}
    <h2 class="ps-3">Crear Cliente</h2>
    {{ include('cliente/_form.html.twig') }}

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('cliente_index') }}">Volver a la lista</a>
        </div>
    </div>
{% endblock %}

templates/cliente/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cliente{% endblock %}

{% block content %}
    <h1>Cliente</h1>

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cliente.id }}</td>
            </tr>
            <tr>
                <th>Nit</th>
                <td>{{ cliente.nit }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ cliente.nombre }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ cliente.direccion }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ cliente.telefono }}</td>
            </tr>
            <tr>
                <th>Administrador</th>
                <td>{{ cliente.contacto }}</td>
            </tr>
            <tr>
                <th>Celular</th>
                <td>{{ cliente.celular }}</td>
            </tr>
            <tr>
                <th>Correo_electronico</th>
                <td>{{ cliente.correoElectronico }}</td>
            </tr>
            <tr>
                <th>Observaciones</th>
                <td>{{ cliente.observaciones }}</td>
            </tr>
            <tr>
                <th>F_creacion</th>
                <td>{{ cliente.fCreacion ? cliente.fCreacion|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>F_actualizacion</th>
                <td>{{ cliente.fActualizacion ? cliente.fActualizacion|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <div class="row my-3">
        <div class="col-2">
            <a class="btn btn-primary w-100" href="{{ path('cliente_index') }}">Volver a la lista</a>
        </div>
    </div>

    <a href="{{ path('cliente_edit', {'slug': cliente.slug}) }}">edit</a>

    {{ include('cliente/_delete_form.html.twig') }}
{% endblock %}